### ISSUE TITLE
Suggestion: Make mod available in MC1.20.1 - Tested with 1.20.4 version

### ISSUE THREAD

**Issue by xExthasex** [Kim-Lan/strong-leads#2]
I tested the mod in 1.20.1 and got into no problems with most of the features testet.
You should consider to test it yourself and change the dependency of MC to 1.20.1 or even lower.

Great mod, appreciate the afford!

**Comment by xExthasex** [comment]
After a couple of "restarts" the mod crashes.

```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.
Time: 2024-10-28 00:32:42
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'betterleads' at 'com.github.quaoz.betterleads.BetterLeads'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at knot//net.minecraft.class_310.<init>(class_310.java:458)
at knot//net.minecraft.client.main.Main.main(Main.java:211)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[leashable_watercreatures]" defined twice in its table.
at knot//com.electronwill.nightconfig.toml.TableParser.checkDuplicateKey(TableParser.java:118)
at knot//com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:69)
at knot//com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:61)
at knot//com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:45)
at knot//com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:18)
at knot//com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:99)
at knot//com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:216)
at knot//com.electronwill.nightconfig.core.file.AsyncFileConfig.loadNow(AsyncFileConfig.java:189)
at knot//com.electronwill.nightconfig.core.file.AsyncFileConfig.load(AsyncFileConfig.java:270)
at knot//com.electronwill.nightconfig.core.file.AutoreloadFileConfig.load(AutoreloadFileConfig.java:47)
at knot//com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:131)
at knot//com.github.quaoz.betterleads.BetterLeadsConfig.load(BetterLeadsConfig.java:32)
at knot//com.github.quaoz.betterleads.BetterLeads.onInitialize(BetterLeads.java:22)
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
... 6 more
```

**Comment by xExthasex** [comment]
You could still consider fixing and updating it to 1.20.1 if you want. Thank you!

**Comment by meowisme** [comment]
I second this request.
